language: python
cache: pip
notifications:
  email: false
sudo: required
services:
  - docker
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    packages:
      - openssh-server
      - rpm
      - dpkg
      - cmake

install:
  - pip install flake8 jinja2 sphinx sphinx_rtd_theme
  - python setup.py build_ext --inplace
  - eval "$(ssh-agent -s)"

script:
  - nosetests
  - flake8 ssh
  - python setup.py sdist
  - cd dist; pip install *; cd ..
  - cd doc; make html; cd ..
jobs:
  include:

    - &osx-wheels
      stage: build packages
      os: osx
      osx_image: xcode8
      env:
        - PYENV: 3.6.4
        - SYSTEM_LIBSSH: 1
      before_install:
        - brew update
        - brew link --overwrite python@2 || brew install python@2 || brew link --overwrite python@2
        - which python2
        - sudo -H pip2 install twine
        - which twine
        - sudo ci/install-ssh.sh
        - cp /usr/local/lib/libssh*.dylib .
        - mkdir -p wheels
      install:
        - sudo -H pip2 install -U delocate wheel pip setuptools
        - ls -lh
      script:
        - pip2 wheel --no-deps .
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh.session import Session; Session()"
        - cd ..; pwd
        - mv -f *.whl wheels/
        - ./ci/travis/pyenv-wheel.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheels/*.whl;
          fi
      language: generic
      python: skip

    - <<: *osx-wheels
      osx_image: xcode9.2

    - <<: *osx-wheels
      osx_image: xcode9.4

    - <<: *osx-wheels
      osx_image: xcode8
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH: 1
      install: skip
      script:
        - ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.2
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH: 1
      install: skip
      script:
        - ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.4
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH: 1
      install: skip
      script:
        - ./ci/travis/pyenv-wheel.sh

    - stage: build wheels
      os: linux
      python: 3.6
      install:
        - pip install twine
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheelhouse/*.whl;
          fi
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            repo: ParallelSSH/ssh-python
            tags: true
          distributions: sdist
          user: pkittenis
          password:
            secure: "RIG3Q+TI42oO9C8X0psryqp4IiZS9aWjhDav1WmvEM1BjmyvJDdxoM+Q29XA7POkmfpPHx165bzMCbJo6/366lmAjS2IaBU1EHmO8uwx4FwUgDmSy0IswnRcSnWbzv793Qpituu9mkXRUmgjIlz7qZxYi55Zry1nOCpZxg2UREk8ILVBjszxN77UlmySztF9IZETeKvaPyuCVMEi/0804hNfMMsigshlqz0roEiXONdzRxCWk0zN8XqIBr7Oro03CYse6dha7evZ1K9cBq5wVmLvxtBcWYuQMt8NwH9QmdgeDjrLkE7L3E0DOcKkmGwSaRCZheRIIox64/4LWmHVhu3ntxu+UoSicBRXDVCECcNZHzlfLOkGH+e4pISL0J2dm9M+gyllxTRDi6lIDLRumPhfVpFNJ5BKAuwGUNYSe0qKCBdpSNlN1AXqtjBjtfAN/WdGfsBmp54NhWQDbHMLtnoBlNrFG19aKk2UvgES4XHxcmKYC45KW3HE0oK+Ep7yUweBtrtaneTV9bi6smBrJfaxn6UNnY6L2OowbAwlcZBbRDaIoh160j9j62ezY6Ry+UGL8Z1eNUnafd5dBxbZhFVTQbxC9g/Yy6uHmOdlyAM5QlFlnj7ib0HcCKr4DEq4Uy+xyrSlHibU8vPsxBt/OPx0vN+5alXnX1asFpuO0ro="
